channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - jupyter-server-proxy
  - code-server >=3.2
  - snakemake
  - graphviz =2.42
  - matplotlib =3.3
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7
  - pysam =0.15
