channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - numpy
  - jupyter-server-proxy
  - code-server >=3.2
  - snakemake
  # - snakemake-minimal >=5.24.1
  - jinja2
  - networkx
  - matplotlib
  - graphviz
  - bcftools
  - samtools
  - bwa
  - pysam
